<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php $menuClass = $block->getMenu()->getCssClass() ?>
    <nav class="<?= $menuClass ?>">
        <ul class="<?= $menuClass ?>__list" id="menu-desktop">
            <?php foreach ($block->getNodes() as $node): ?>
                <?php
                    $childrenLevel = $node->getLevel() + 1;
                    $children = $this->getNodes($childrenLevel, $node);
                    $node->setIsParent((bool) $children);
                    $parentClass = $children ? ' ' . $menuClass . '__item--parent' : '';
                    $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                    $itemClasses = $parentClass . $additionalClasses;
                ?>
                <li class="<?= $menuClass ?>__item<?= $itemClasses ?>">
                    <?php echo $block->renderMenuNode($node) ?>
                    <?php echo $block->renderSubmenu($children, $node, $childrenLevel) ?>
                </li>
            <?php endforeach ?>
        </ul>
    </nav>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "focus-element": {
                "transition": 250,
                "media": {
                    "width": 768,
                    "type": "min"
                },
                "events": {
                    "open": [
                        {
                            "trigger": "nav .epi-menu-main__item--parent",
                            "event": "mouseenter",
                            "elem": ".page-header, .sections.nav-sections"
                        }
                    ],

                    "close": [
                        {
                            "trigger": "nav .epi-menu-main__item--parent",
                            "event": "mouseleave"
                        }
                    ]
                }
            }
        }
    }
</script>
