<script type="text/x-magento-init">
    {
        ".brand-image-slider": {
            "js/slick-template": {
                "slick": {
                    "slidesToShow": 5,
                    "dots": false,
                    "responsive": [
                        {
                            "breakpoint": 850,
                            "settings": {
                                "slidesToShow": 4
                            }
                        },
                        {
                            "breakpoint": 768,
                            "settings": {
                                "arrows": false,
                                "slidesToShow": 4
                            }
                        },
                        {
                            "breakpoint": 660,
                            "settings": {
                                "arrows": false,
                                "slidesToShow": 3
                            }
                        },
                        {
                            "breakpoint": 500,
                            "settings": {
                                "arrows": false,
                                "slidesToShow": 2
                            }
                        }
                    ]
                }
            }
        }
    }
</script>
