<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
                
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                        class="product photo product-item-photo"
                        tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <div class="product-item-attr">
                                <?php 
                                    $empresa = $_product->getData('company_approval_certificate');
                                    $codEpi = $_product->getData('sku');
                                    $modFabricante = $_product->getData('model_reference');
                                ?>
                                <?php if($empresa): ?>
                                    <p class="attribute modelo">
                                        <span class="value"><?= $empresa ?></span>
                                    </p>
                                <?php endif; ?>

                                <?php /* Para onda 2 */ ?>
                                <?php if(false): ?>
                                    <p class="attribute">
                                        <span class="title">Cód. Cliente: </span><span class="value">121212</span>
                                    </p>
                                <?php endif; ?>

                                <?php if($codEpi): ?>
                                    <p class="attribute">
                                        <span class="title">Cód. Epi: </span><span class="value"><?= $codEpi ?></span>
                                    </p>
                                <?php endif; ?>

                                <?php if($modFabricante): ?>
                                    <p class="attribute">
                                        <span class="title">Mod. Fabricante: </span><span class="value"><?= $modFabricante ?></span>
                                    </p>
                                <?php endif; ?>
                            </div>

                            <?php //Retirar esse if na onda 2 ?>
                            <?php if(false): ?>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                                <?php if ($_product->isAvailable()) :?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="interest-free">
                                    <?= $this->getLayout()
                                        ->createBlock('custom\InstallmentPrice\Block\Lists\Installment')
                                        ->setTemplate('Custom_InstallmentPrice::list/installment.phtml')
                                        ->setProduct($_product)
                                        ->toHtml();
                                    ?>
                                </div>
                            <?php endif; ?>

                            <!-- <p class="product-attr">158948578B</p> -->

                            <?php //Retirar esse if na onda 2 ?>
                            <?php if(false): ?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                            <?php if ($_product->isSaleable()) :?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                    data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                                    action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                    method="post">
                                                    <input type="hidden"
                                                        name="product"
                                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                        value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtmlAttr(__('Buy')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= $block->escapeHtml(__('Buy')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else :?>
                                                <?php if ($_product->isAvailable()) :?>
                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else :?>
                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>

                                    </div>
                                    <?php if ($showDescription) :?>
                                        <div class="product description product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                            title="<?= /* @noEscape */ $_productNameStripped ?>"
                                            class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>

                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
