<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Company\Block\Company\CompanyProfile $block
 */
$company = $block->getCustomerCompany();
?>
<?php if ($block->isViewAccountAllowed()) : ?>
<div class="block block-company-profile-account">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Account Information')) ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-account-information">
            <div class="box-content">
                <?php
                $companyName = $block->escapeHtml($company->getCompanyName());
                $companyName .= (!empty($company->getLegalName()))
                    ? ' (' . $block->escapeHtml($company->getLegalName()) . ')' : '';
                ?>
                <p><?= /* @noEscape */ $companyName ?>
                    <?php
                    if (!empty($company->getCompanyEmail())) : ?>
                        <br/><?= $block->escapeHtml($company->getCompanyEmail()) ?>
                        <?php
                    endif; ?>
                    <?php
                    if (!empty($company->getVatTaxId())) : ?>
                        <br/><?= $block->escapeHtml(__('VAT/TAX ID: '))
                            . $block->escapeHtml($company->getVatTaxId()); ?>
                        <?php
                    endif; ?>
                    <?php
                    if (!empty($company->getResellerId())) : ?>
                    <br/><?= $block->escapeHtml(__('Re-seller ID: '))
                        . $block->escapeHtml($company->getResellerId()); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isViewAddressAllowed()) : ?>
<div class="block block-company-profile-address">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Legal Address')) ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-address-information">
            <div class="box-content">
                <address>
                    <?php if (!$block->isCompanyAddressDisplayed($company)) : ?>
                        <?= $block->escapeHtml(
                            __('You have no other address entries in your address book.')
                        ); ?><br />
                    <?php else : ?>
                        <?php if (!empty($company->getStreet())) : ?>
                            <?= $block->escapeHtml($block->getCompanyStreetLabel($company)) ?><br />
                        <?php endif; ?>
                        <?= $block->escapeHtml($block->getCompanyAddressString($company)) ?><br />
                        <?= $block->escapeHtml($block->getCompanyCountryLabel($company)) ?><br />
                        <?= $block->escapeHtml(__('T: %1', $company->getTelephone())) ?>
                    <?php endif; ?>
                    <br />
                </address>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isViewContactsAllowed()) : ?>
<div class="block block-company-profile-contacts">
    <div class="block-title">
        <strong>
            <?= $block->escapeHtml(__('Contacts')) ?>
        </strong>
    </div>
    <div class="block-content">
        <div class="box box-contact-information">
            <strong class="box-title">
                <span>Atendente Epi</span>
            </strong>
            <div class="box-content">
                Daniel Castello<br />
                daniel@protcap.com.br
            </div>
        </div>

        <div class="box box-contact-information">
            <strong class="box-title">
                <span>Executivo(a) de contas Epi</span>
            </strong>
            <div class="box-content">
                Carina Andrade<br />
                carina.andrade@protcap.com.br
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
