<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<p class="toolbar-amount m-0" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1) : ?>
        <?php
        echo $block->escapeHtml('Mostrando <span class="font-bold"><span class="toolbar-number">' . $block->getFirstNum() . '</span>-<span class="toolbar-number">' . $block->getLastNum() . '</span></span> de <span class="toolbar-number font-bold">' . $block->getTotalNum() . '</span>', ['span']);
        ?>
    <?php elseif ($block->getTotalNum() == 1) : ?>
        <?php
        echo $block->escapeHtml('<span class="font-bold"><span class="toolbar-number">' . $block->getTotalNum() . '</span> item</span>', ['span']);
        ?>
    <?php else : ?>
        <?php
        echo $block->escapeHtml('<span class="font-bold"><span class="toolbar-number">' . $block->getTotalNum() . '</span> itens</span>', ['span']);
        ?>
    <?php endif; ?>
</p>