<div class="history-sort">
    <div class="sort-by">
        <label for="sorter">Ordenar por</label>
        <select name="sortby" id="sortby">
            <option value="1">Ordens de compra</option>
            <option value="2">Dados do pedido</option>
            <option value="3">OC</option>
            <option value="4">NF</option>
        </select>
    </div>
    <div class="links">
        <div class="print-container">
            <a href="#" onclick="print();" class="print">Imprimir</a>
        </div>
        <div class="export-container">
            <a href="#" class="export">Exportar</a>
        </div>
    </div>
</div>
